name: "Install deps"
description: "Installs system dependencies required for building the project (liburing-dev, libssl-dev, pkg-config, build-essential)"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        
        echo "Updating package lists..."
        if ! apt-get update; then
          echo "ERROR: Failed to update package lists. Check network connectivity and repository configuration." >&2
          exit 1
        fi
        
        echo "Installing build dependencies..."
        if ! apt-get install -y \
          liburing-dev libssl-dev pkg-config build-essential; then
          echo "ERROR: Failed to install required packages. Check package availability and disk space." >&2
          exit 1
        fi

        echo "Installing nfpm for .deb packaging..."
        # Try to install nfpm from apt, fallback to manual install
        if ! apt-get install -y nfpm; then
          echo "nfpm not available in apt, installing manually..."
          curl -sSfL https://github.com/goreleaser/nfpm/releases/download/v2.35.3/nfpm_2.35.3_Linux_x86_64.tar.gz -o /tmp/nfpm.tar.gz
          tar -xzf /tmp/nfpm.tar.gz -C /tmp
          mv /tmp/nfpm /usr/local/bin/nfpm
          chmod +x /usr/local/bin/nfpm
        fi

        echo "Successfully installed all dependencies."

